### ISSUE TITLE
info/advertisement

### ISSUE THREAD

**Issue by hakavlad** [bplotnick/oomscored#1]
>user plotnick should always have a higher score and user root should have a lower score

You can do it with userspace oom-killer https://github.com/hakavlad/nohang, use matching UID with regex pattern to control choosing victim.

Features:
- impact on the badness of processes via matching their names, cmdlines and UIDs with regular expressions
https://github.com/hakavlad/nohang#some-features

**Comment by bplotnick** [comment]
Nice! Thanks for letting me know. My project is pretty old and, as far as I know, not used by anyone (including me), but I’ll add a note about user-space OOM killers nonetheless. It seems like an approach that is more understandable to users anyway.
